# Generated by Django 5.0.6 on 2024-06-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrival_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA61997343-2102-447c-ORDER', max_length=30, unique=True),
        ),
    ]
