# Generated by Django 5.0.6 on 2024-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_order_arrival_time_alter_order_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA6c9878d1-4399-4a37-ORDER', max_length=30, unique=True),
        ),
    ]
