# Generated by Django 5.0.6 on 2024-06-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_remove_order_arrival_time_alter_order_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA9bc45f61-402f-4db8-ORDER', max_length=30, unique=True),
        ),
    ]
