# Generated by Django 5.0.6 on 2024-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='EXWA4a1a340d-7cfc-4381-ORDER', max_length=30, unique=True),
        ),
    ]
